language: c

sudo: false

env:
  global:
    - LUAROCKS=2.2.0
  matrix:
    # Lua 5.1 is separate because it requires Lua BitOp.
    - LUA=lua5.2
    - LUA=lua5.3
    - LUA=luajit

branches:
  only:
    - master

before_install:
  - source .travis/setenv_lua.sh

install:
  - luarocks install luasocket
  - luarocks install penlight
  - luarocks install cwtest

matrix:
  include:
    - env: LUA=lua5.1
      install:
        - luarocks install luasocket
        - luarocks install penlight
        - luarocks install cwtest
        - luarocks install luabitop

script:
  - lua fakeredis.test.lua

notifications:
  email:
    on_success: change
    on_failure: always
